# 项目配置文件
config_version: "1.0.0"

app:
  api_port: 8000
  api_url: http://localhost:8000/api
  name: 3AI
  port: 3000
  url: http://localhost:3000

backup_dir: "s:/3AI/bak"
created_at: '2025-06-19T17:15:34.936127'
project_name: "3AI"
project_version: "1.0.0"

# 性能配置
performance:
  max_concurrent_requests: 100
  request_timeout: 30000
  memory_limit: "512MB"
  cpu_limit: "1000m"
  cache_size: 100
  connection_pool_size: 10
  worker_processes: 4
  enable_compression: true
  static_cache_ttl: 86400

# 文件类型配置
file_types:
  allowed_extensions:
    - ".py"
    - ".js"
    - ".ts"
    - ".jsx"
    - ".tsx"
    - ".md"
    - ".txt"
    - ".json"
    - ".yaml"
    - ".yml"
    - ".html"
    - ".css"
    - ".scss"
    - ".less"
    - ".sql"
    - ".sh"
    - ".bat"
    - ".ps1"
  max_file_size: 10485760  # 10MB
  encoding: "utf-8"
  line_ending: "auto"  # auto, lf, crlf
  exclude_patterns:
    - "*.pyc"
    - "*.pyo"
    - "*.pyd"
    - "__pycache__"
    - "node_modules"
    - ".git"
    - "*.log"
    - "*.tmp"

# 规则配置
rules:
  validation:
    strict_mode: false
    allow_empty_files: true
    require_documentation: true
    enforce_naming_conventions: true
  code_quality:
    max_line_length: 120
    max_function_length: 50
    max_file_length: 1000
    require_type_hints: true
    enforce_docstrings: true
  security:
    scan_for_secrets: true
    require_https: false
    validate_inputs: true
    sanitize_outputs: true
  compliance:
    license_check: false
    dependency_audit: true
    vulnerability_scan: true

# 日志配置
logging:
  level: info
  dir: ./logs
  max_size: 10m
  max_files: 5
  date_pattern: YYYY-MM-DD
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  rotation: daily
  compress: true
  backup_count: 30

# Git配置
git:
  repo_dir_name: "github_repo"
  default_branch: "main"
  auto_push: true
  commit_message_prefix: "自动备份"
database:
  dev_name: 3AI_dev_db
  host: localhost
  name: 3ai_db
  password: password
  port: 5432
  test_name: 3AI_test_db
  url_template: postgresql://{username}:{password}@{host}:{port}/{database_name}
  username: postgres
environment:
  # 基础配置
  app:
    name: "3AI工作室"
    version: 1.0.0
    url: http://localhost:3000
    api_url: http://localhost:8000
    port: 3000
    api_port: 8000
  
  # 数据库配置
  database:
    url: postgresql://postgres:password@localhost:5432/3AI_db
    host: localhost
    port: 5432
    name: 3AI_db
    user: postgres
    password: password
    pool_min: 2
    pool_max: 10
    pool_idle_timeout: 30000
    test_url: postgresql://postgres:password@localhost:5432/3AI_test_db
  
  # Redis配置
  redis:
    url: redis://localhost:6379/0
    host: localhost
    port: 6379
    db: 0
    password: ""
    session_db: 1
  
  # 安全配置
  security:
    session_secret: your-session-secret-key-change-this
    session_max_age: 86400000
    jwt_secret: your-super-secret-jwt-key-change-this-in-production
    jwt_expires_in: 7d
    jwt_refresh_expires_in: 30d
    encryption_key: your-32-character-encryption-key
    cors_origin: http://localhost:3000
    cors_credentials: true
  
  # 文件存储配置
  storage:
    upload_dir: ./uploads
    max_file_size: 10485760
    allowed_file_types: jpg,jpeg,png,gif,pdf,doc,docx,txt
    # aws_access_key_id: your-aws-access-key
    # aws_secret_access_key: your-aws-secret-key
    # aws_region: us-east-1
    # aws_s3_bucket: your-s3-bucket
  
  # 邮件配置
  mail:
    smtp_host: smtp.gmail.com
    smtp_port: 587
    smtp_secure: false
    smtp_user: your-email@gmail.com
    smtp_pass: your-app-password
    from_name: "3AI工作室"
    from_address: noreply@3ai.studio
  
  # 日志配置已移至顶层
  
  # 外部服务配置
  external_services:
    openai_api_key: your-openai-api-key
    openai_model: gpt-4
    openai_max_tokens: 2000
    # anthropic_api_key: your-anthropic-api-key
    # google_ai_api_key: your-google-ai-api-key
  
  # 监控配置
  monitoring:
    # sentry_dsn: your-sentry-dsn
    # new_relic_license_key: your-newrelic-key
    # ga_tracking_id: your-ga-tracking-id
    health_check_endpoint: /health
    health_check_interval: 30000
  
  # 网络配置
  network:
    host: localhost
    preview_host: localhost
    default_ports:
      frontend: 3000
      api: 8000
      preview: 3000
      dev_server: 3000
  
  # 缓存配置
  cache:
    ttl: 3600
    max_items: 1000
    static_max_age: 31536000
  
  # 限流配置
  rate_limit:
    window_ms: 900000
    max_requests: 100
    upload_limit: 10
  
  # 环境特定配置
  development:
    debug: true
    log_level: DEBUG
    webpack_dev_server_host: localhost
    webpack_dev_server_port: 3000
    webpack_hot_reload: true
    api_docs_enabled: true
    api_docs_path: /docs
    debug_mode: true
    verbose_logging: false
  
  production:
    debug: false
    log_level: INFO
    # ssl_cert_path: /path/to/cert.pem
    # ssl_key_path: /path/to/key.pem
    # cluster_workers: auto
  
  test:
    debug: true
    log_level: DEBUG
    timeout: 30000
    coverage_threshold: 80
# Git配置已在上方定义，此处重复配置已删除
migration:
  cleanup_dirs:
  - __pycache__
  - node_modules
  - .git
  - logs
  - bak
  reset_files:
  - .env
  - docs/02-开发/开发日志.md
  - docs/02-开发/tasks.json
  update_patterns:
  - '*.md'
  - '*.yaml'
  - '*.yml'
  - '*.json'
  - '*.js'
  - '*.py'
  - '*.sh'
  - .env*
paths:
  root: "s:/3AI"
  backup_dir: "s:/3AI/bak"
  docs_dir: "s:/3AI/docs"
  logs_dir: "s:/3AI/logs"
  project_dir: "s:/3AI/project"
  required_dirs:
  - src
  - logs
  - bak
  - docs
  - tools
  - project
  required_files:
  - README.md
  - requirements.txt
  tools_dir: "s:/3AI/tools"
project:
  created_at: '2025-06-20T00:11:18.534319'
  name: 3AI
  root: "s:/3AI"
  updated_at: '2025-06-20T00:11:18.534332'
project_description: 3AI项目
project_root: ''
structure_check:
  # 基本配置
  standard_list_file: docs/01-设计/目录结构标准清单.md
  report_dir: logs/检查报告
  report_name_format: 目录结构检查报告_{timestamp}.md
  
  # 检查配置
  excluded_dirs: 
    - .git
    - node_modules
    - __pycache__
    - .pytest_cache
    - venv
    - .venv
    - env
    - .env
    - dist
    - build
    - .idea
    - .vscode
    - .DS_Store
    - Thumbs.db
  
  excluded_files:
    - .DS_Store
    - Thumbs.db
    - "*.pyc"
    - "*.pyo"
    - "*.pyd"
    - .gitkeep
    - .keep
    - "*.tmp"
    - "*.temp"
    - "*.log"
  
  # 允许的隐藏文件/目录
  allowed_hidden_items:
    - .env
    - .env.example
    - .gitignore
    - .dockerignore
    - .eslintrc.js
    - .prettierrc
    - .pre-commit-config.yaml
    - .devcontainer
    - .github
    - .venv
  
  # 特殊目录配置
  special_dirs:
    bak:
      - github_repo
      - 迁移备份
      - 专项备份
      - 待清理资料
      - 常规备份
    logs:
      - 工作记录
      - 检查报告
      - 其他日志
      - archive
  
  excluded_dirs_for_redundancy: [bak, logs]
  
  # 性能优化配置
  max_depth: 10
  skip_deep_nested_dirs: true
  
  # 默认规则（当标准文件解析失败时使用）
  default_forbidden_patterns:
    - "*.tmp"
    - "*.bak"
    - "*.swp"
    - "*.log"
    - "*~"
    - "Thumbs.db"
    - ".DS_Store"
    - "Everything.db"
    - "*.db"
    - "*.sqlite"
  
  # 项目根目录严格检查
  root_directory_rules:
    # 只允许存在的标准目录
    allowed_directories:
      - "bak"
      - "docs"
      - "logs"
      - "project"
      - "tools"
    
    # 严格禁止的目录模式
    forbidden_directory_patterns:
      - "config*"
      - "example*"
      - "sample*"
      - "temp*"
      - "tmp*"
      - "cache*"
      - "test*"
    
    # 严格禁止的文件模式
    forbidden_file_patterns:
      - "*.db"
      - "*.sqlite"
      - "Everything.db"
      - "*.log"
      - "*.tmp"
  
  default_naming_rules:
    docs: "^[\u4e00-\u9fa5a-zA-Z0-9_ -]+\\.(md|txt)$"
    tools: "^[a-zA-Z0-9_-]+\\.(py|js|sh|bat|ps1)$"
    config: "^[a-zA-Z0-9_-]+\\.(json|yaml|yml|ini|conf)$"
template:
  default_description: AI项目开发框架
  default_project_name: 3AI
  variables:
  - PROJECT_NAME
  - PROJECT_DESCRIPTION
  - CREATED_AT
  - UPDATED_AT
updated_at: '2025-06-19T17:15:34.936137'
mcp:
  memory:
    storage_path: "docs/02-开发/memory.json"  # 相对于项目根目录
    isolation_mode: "project"  # project | global | custom
  task_manager:
    storage_path: "docs/02-开发/tasks.json"
    isolation_mode: "project"
